import 'package:supabase_flutter/supabase_flutter.dart';

import '../domain/day_archive.dart';
import '../domain/task.dart';

String _todayLocalDate() {
  final now = DateTime.now();
  return '${now.year.toString().padLeft(4, '0')}-'
      '${now.month.toString().padLeft(2, '0')}-'
      '${now.day.toString().padLeft(2, '0')}';
}

/// Direct Supabase reads/writes for the Today board and Pomodoro timer --
/// deliberately NOT going through the chat Edge Function/LLM. RLS (user_id =
/// auth.uid()) is what keeps this safe without an extra user_id filter here.
class TaskRepository {
  final SupabaseClient _client;
  TaskRepository(this._client);

  Stream<List<Task>> watchTodayTasks() {
    return _client
        .from('tasks')
        .stream(primaryKey: ['id'])
        .eq('task_date', _todayLocalDate())
        .order('position')
        .map((rows) => rows.map(Task.fromRow).toList());
  }

  Future<void> updateTaskStatus(String taskId, TaskStatus status) async {
    final patch = <String, dynamic>{'status': taskStatusToString(status)};
    if (status == TaskStatus.done) {
      patch['completed_at'] = DateTime.now().toIso8601String();
    }
    await _client.from('tasks').update(patch).eq('id', taskId);
  }

  /// Logs a completed/interrupted pomodoro directly (no LLM round trip) and
  /// writes the "该任务是否完成？" check-in as a plain chat_messages row so it
  /// shows up in the transcript without having been generated by the model.
  Future<void> logPomodoroAndPromptCheckIn({
    required String taskId,
    required DateTime startedAt,
    required DateTime endedAt,
    required String outcome,
  }) async {
    final userId = _client.auth.currentUser!.id;
    await _client.from('pomodoro_sessions').insert({
      'task_id': taskId,
      'user_id': userId,
      'started_at': startedAt.toIso8601String(),
      'ended_at': endedAt.toIso8601String(),
      'duration_sec': endedAt.difference(startedAt).inSeconds,
      'outcome': outcome,
    });
    if (outcome == 'completed') {
      await _client.from('chat_messages').insert({
        'user_id': userId,
        'role': 'assistant',
        'content': [
          {'type': 'text', 'text': '番茄钟结束，该任务是否完成？(完成/未完/继续)'}
        ],
      });
    }
  }

  Future<List<DayArchive>> getHistory({required DateTime start, required DateTime end}) async {
    final rows = await _client
        .from('day_archives')
        .select()
        .gte('archive_date', start.toIso8601String().substring(0, 10))
        .lte('archive_date', end.toIso8601String().substring(0, 10))
        .order('archive_date', ascending: false);
    return (rows as List<dynamic>).cast<Map<String, dynamic>>().map(DayArchive.fromRow).toList();
  }
}
